---
title: "Figure4_CMP"
output: html_document
date: "2024-05-28"
---

#Figure 4c
```{r}
cmc.hyper <- read.csv("~/Desktop/KAIST/HF/DEG/SejongIn_P_Hyp_0vs1_FullROI_N_cellselection_Y_Cardiomyocytes_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2023-06-24condition1-condition0.csv")
ec.hyper <- read.csv("~/Desktop/KAIST/HF/DEG/SejongIn_P_Hyp_0vs1_FullROI_N_cellselection_Y_Endothelial_cells_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2023-06-24condition1-condition0.csv")
fb.hyper <- read.csv("~/Desktop/KAIST/HF/DEG/SejongIn_P_Hyp_0vs1_FullROI_N_cellselection_Y_Fibroblasts_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2024-04-24condition1-condition0.csv")

cmc.degen <- read.csv("~/Desktop/KAIST/HF/DEG/SejongIn_P_Deg_0vs1_FullROI_N_cellselection_Y_Cardiomyocytes_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2023-06-24condition1-condition0.csv")
ec.degen <- read.csv("~/Desktop/KAIST/HF/DEG/SejongIn_P_Deg_0vs1_FullROI_N_cellselection_Y_Endothelial_cells_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2023-06-24condition1-condition0.csv")
fb.degen <- read.csv("~/Desktop/KAIST/HF/DEG/SejongIn_P_Deg_0vs1_FullROI_N_cellselection_Y_Fibroblasts_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2024-04-24condition1-condition0.csv")

cmc.fibro <- read.csv("~/Desktop/KAIST/HF/DEG/SejongIn_P_Fib_0vs1_FullROI_N_cellselection_Y_Cardiomyocytes_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2023-06-24condition1-condition0.csv")
ec.fibro <- read.csv("~/Desktop/KAIST/HF/DEG/SejongIn_P_Fib_0vs1_FullROI_N_cellselection_Y_Endothelial_cells_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2023-06-24condition1-condition0.csv")
fb.fibro <- read.csv("~/Desktop/KAIST/HF/DEG/SejongIn_P_Fib_0vs1_FullROI_N_cellselection_Y_Fibroblasts_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2024-04-24condition1-condition0.csv")

cmc.disarray <- read.csv("~/Desktop/KAIST/HF/DEG/SejongIn_P_Disarray_0vs1_FullROI_N_cellselection_Y_Cardiomyocytes_ROI_large_Vent_LV_DsSelect_NES_HCMP_Y_OL_pcaplot_outlier_RE_PID_Fixation.interval_KR_Y2023-06-24condition1-condition0.csv")
ec.disarray <- read.csv("~/Desktop/KAIST/HF/DEG/SejongIn_P_Disarray_0vs1_FullROI_N_cellselection_Y_Endothelial_cells_ROI_large_Vent_LV_DsSelect_NES_HCMP_Y_OL_pcaplot_outlier_RE_PID_Fixation.interval_KR_Y2023-06-24condition1-condition0.csv")
```

```{r}
p.histo <- list()
cmc.histo.list <- list(cmc_hyper = cmc.hyper, cmc_degen = cmc.degen, cmc_fibro = cmc.fibro, cmc_disarray = cmc.disarray)
ec.histo.list <- list(ec.hyper, ec.degen, ec.fibro, ec.disarray)
```

```{r}
for (i in 1:length(cmc.histo.list)){
  cmc.dcmp <- cmc.histo.list[[i]]
  ec.dcmp <- ec.histo.list[[i]]
  
  df1 <- cmc.dcmp %>% select(SYMBOL, logFC, adj.P.Val)
  df2 <- ec.dcmp %>% select(SYMBOL, logFC, adj.P.Val)
  df <- merge(df1, df2, by = "SYMBOL", all = T)
  
  tmp2 <- df %>% 
    mutate(logFC.x = case_when(is.na(logFC.x) ~ 0,  TRUE ~ logFC.x),
           logFC.y = case_when(is.na(logFC.y) ~ 0, TRUE ~ logFC.y),
           
           adj.P.Val.y = case_when(is.na(adj.P.Val.y) ~ 1, TRUE ~ adj.P.Val.y),
           adj.P.Val.x = case_when(is.na(adj.P.Val.x) ~ 1, TRUE ~ adj.P.Val.x),
           
           ident = case_when(adj.P.Val.x > 0.05 & adj.P.Val.y > 0.05 ~ "NS_NS",
                             adj.P.Val.x > 0.05 & adj.P.Val.y <= 0.05 ~ "NS_sig",
                             adj.P.Val.x <= 0.05 & adj.P.Val.y > 0.05 ~ "sig_NS",
                             adj.P.Val.x <= 0.05 & adj.P.Val.y <= 0.05 ~ "sig_sig"),
           
           gene_label_2 = case_when(grepl("^MT-|RPL|RPS|KRT|IGL|IGK", SYMBOL) ~ "",
                                    # gene %in% c("CD8A", "CD8B", "CD3D", "CD3E") ~ "",
                                    ident == "NS_NS" ~ "", TRUE ~ SYMBOL),
           
           updown = case_when(logFC.x > 0.5 & adj.P.Val.x < 0.05 & logFC.y > 0.5 & adj.P.Val.y < 0.05 ~ "UP_both",
                              logFC.x < -0.5 & adj.P.Val.x < 0.05 & logFC.y < -0.5 & adj.P.Val.y < 0.05 ~ "DOWN_both",
                              logFC.x > 0.5 & adj.P.Val.x < 0.05 ~ "UP_cmc",
                              logFC.y > 0.5 & adj.P.Val.y < 0.05 ~ "UP_ec", 
                              logFC.x < -0.5 & adj.P.Val.x < 0.05 ~ "DOWN_cmc",
                              logFC.y < -0.5 & adj.P.Val.y < 0.05 ~ "DOWN_ec",
                              TRUE ~ "NO"), 
           
           gene_label_3 = case_when(updown != "NO" ~ gene_label_2,
                                    TRUE ~ NA), 
           
           pvalue = case_when(adj.P.Val.x > 0.05 & adj.P.Val.y > 0.05 ~ "NS_NS",
                              adj.P.Val.x > 0.05 & (adj.P.Val.y > 0.01 & adj.P.Val.y <= 0.05) ~ "NS_sig",
                              (adj.P.Val.x > 0.01 & adj.P.Val.x <= 0.05) & adj.P.Val.y > 0.05 ~ "sig_NS",
                              (adj.P.Val.x > 0.01 & adj.P.Val.x <= 0.05) & (adj.P.Val.y > 0.01 & adj.P.Val.y <= 0.05) ~ "sig_sig",
                              adj.P.Val.x > 0.05 & adj.P.Val.y <= 0.01 ~ "NS_sigX",
                              adj.P.Val.x <= 0.01 & adj.P.Val.y > 0.05 ~ "sigX_NS",
                              (adj.P.Val.x > 0.01 & adj.P.Val.x <= 0.05) & adj.P.Val.y <= 0.01 ~ "sig_sigX",
                              adj.P.Val.x <= 0.01 & (adj.P.Val.y > 0.01 & adj.P.Val.y <= 0.05) ~ "sigX_sig",
                              adj.P.Val.x <= 0.01 & adj.P.Val.y <= 0.01 ~ "sigX_sigX")
           
    ) %>% select(SYMBOL, logFC.x, logFC.y, adj.P.Val.x, adj.P.Val.y, ident, gene_label_2, updown, gene_label_3, pvalue) #%>%  filter(!is.na(gene_label_3))
  
  gene <- tmp2[order(tmp2$logFC.x, decreasing = T), ] %>% head(10) %>% pull(gene_label_3)
  gene <- c(gene, tmp2[order(tmp2$logFC.x, decreasing = F), ] %>% head(10) %>% pull(gene_label_3))
  gene <- c(gene, tmp2[order(tmp2$logFC.y, decreasing = T), ] %>% head(10) %>% pull(gene_label_3))
  gene <- c(gene, tmp2[order(tmp2$logFC.y, decreasing = F), ] %>% head(10) %>% pull(gene_label_3))
  gene <- unique(gene)
  
  tmp2 <- tmp2 %>% 
    mutate(gene_label_4 = case_when(gene_label_3 %in% gene ~ gene_label_3, T ~ ""))%>% 
    select(SYMBOL, logFC.x, logFC.y, adj.P.Val.x, adj.P.Val.y, ident, gene_label_2, updown, gene_label_3, gene_label_4, pvalue)
  
  tmp2 <- tmp2 %>%
    mutate(pvalue_size = case_when(
      pvalue == "NS_NS" ~ 1,
      pvalue == "NS_sig" ~ 2,
      pvalue == "sig_NS" ~ 2,
      pvalue == "sig_sig" ~ 2,
      pvalue == "NS_sigX" ~ 3,
      pvalue == "sigX_NS" ~ 3,
      pvalue == "sig_sigX" ~ 3,
      pvalue == "sigX_sig" ~ 3,
      pvalue == "sigX_sigX" ~ 3,
      TRUE ~ 1  # 기본값
    ),
    pvalue_final = case_when(
      updown != "NO" ~ pvalue_size,
      TRUE ~ 1
    ))
  
  
  p.histo[[i]] <- ggplot(tmp2, aes(logFC.x, logFC.y, label = gene_label_4, col = updown)) + geom_point(aes(size = pvalue_final)) +
    geom_text_repel(size = 4, max.overlaps = 1000, colour = "black") +
    #geom_abline(slope=1, intercept=0) +
    #scale_color_manual(values = col_func) +
    geom_vline(xintercept = 0, linetype = "dashed", color = "darkgrey") +
    geom_hline(yintercept = 0, linetype = "dashed", color = "darkgrey") +
    theme_classic() + 
    theme(axis.title = element_text(face = "bold")) +
    scale_color_manual(values=c("NO" = "#EEEEEE", "DOWN_ec" = "#4DAF4A", "UP_ec" = "#FF7F00", "DOWN_cmc" = "#377EB8", "UP_cmc" = "#E41A1C", "DOWN_both" = "#FFFF33", "UP_both" = "#984EA3")) +
    xlim(-max(abs(tmp2$logFC.x)), max(abs(tmp2$logFC.x))) + 
    ylim(-max(abs(tmp2$logFC.y)), max(abs(tmp2$logFC.y))) +
    scale_size(range = c(1,3))
  
}

```

# figure 4g
```{r}
acp_data_d <- d_join_6[,c("P_Fib3", "ACKR1_CD34_PLVAP_d")]
ggplot(acp_data_d, aes(x = P_Fib3, y = ACKR1_CD34_PLVAP_d, fill = ACKR1_CD34_PLVAP_d)) +
  geom_boxplot(fill = c("#EEE0C9", "#ADC4CE", "#96B6C5")) +
  theme_classic() +
  labs(x = "P_Fib3", y = "ACKR1_CD34_PLVAP_d") +
  stat_compare_means(method = "anova") +
  xlab("") +
  ylab("")

group_by(acp_data_d, P_Fib3) %>%
  summarise(
    count = n(),
    mean = mean(ACKR1_CD34_PLVAP_d, na.rm = T),
    sd = sd(ACKR1_CD34_PLVAP_d, na.rm = T)
  )
```

# figure 4h
```{r}
library(Rcpp)
library(harmony)
library(cowplot)

Idents(HF_cvr_sn2) <- "Names"
A <- subset(HF_cvr_sn2, idents = c("Endothelium"))
endo.list <- SplitObject(A, split.by = "orig.ident")

for (i in 1:length(endo.list)) {
  endo.list[[i]] <- SCTransform(endo.list[[i]], vst.flavor = "v2")
}

HF_harmony <- merge(x = endo.list[[1]], y = endo.list[2:length(endo.list)], merge.data = T, project = "Nature_CVR")

integ_features <- SelectIntegrationFeatures(object.list = endo.list, nfeatures = 3000)

DefaultAssay(HF_harmony) <- "SCT"
VariableFeatures(HF_harmony) <- integ_features

HF_harmony <- RunPCA(HF_harmony, assay = "SCT", npcs = 50)

ElbowPlot(HF_harmony, 50) 

HF_harmony <- RunHarmony(HF_harmony, 
                            group.by.vars = c("orig.ident"), 
                            reduction = "pca", assay.use = "SCT", reduction.save = "harmony")

HF_harmony <- RunUMAP(HF_harmony, reduction = "harmony", assay = "SCT", dims = 1:40)
HF_harmony <- FindNeighbors(object = HF_harmony, reduction = "harmony", dims = 1:40)
#SCAID_harmony <- FindClusters(SCAID_harmony, resolution = c((1:10)/10))
HF_harmony <- FindClusters(HF_harmony, resolution = 0.3)
saveRDS(HF_harmony, "~/JH/HF/HF_endo.rds")
```


```{r}
Idents(HF_endo) <- "SCT_snn_res.0.3"

HF_endo$endo.celltype <- HF_endo$SCT_snn_res.0.3
HF_endo$endo.celltype <- factor(HF_endo$endo.celltype, 
                                levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9"),
                                labels = c("Endothelial cell_cap", "Endothelial cell_vein", "Endothelial cell_artery_2", "Endothelial cell_ISG hi", "Endothelial cell_inflam", "Endothelial cell_artery_1", "Endothelial cell_vein_PLVAP", "Endothelial cell_cap", "Endothelial cell_vein", "Contamination"))

Idents(HF_endo) <- "endo.celltype"
HF_endo$endo.celltype <- factor(HF_endo$endo.celltype, 
                                levels = c("Endothelial cell_artery_1", "Endothelial cell_artery_2", "Endothelial cell_cap", "Endothelial cell_vein", "Endothelial cell_vein_PLVAP", "Endothelial cell_ISG hi", "Endothelial cell_inflam", "Contamination"))

DimPlot(HF_endo, label = F, cols = c("#9AD0C2", "#1A4D2E", "#DFD0B8", "#98ABEE", "#201658", "#795458", "#C08B5C", "#B5C0D0"), group.by = "endo.celltype", raster = F) + ggtitle(NULL)
```

# figure 4i
```{r}
my_palette <- colorRampPalette(c("#FFF5E2", "#C70039", '#900C3F'))(8)

FeaturePlot(HF_endo, features = "ACKR1", raster = F, cols= c("grey90", my_palette))
FeaturePlot(HF_endo, features = "PLVAP", raster = F, cols= c("grey90", my_palette))
FeaturePlot(HF_endo, features = "CCL14", raster = F, cols= c("grey90", my_palette))
```


# figure 4j
```{r}

DotPlot(HF_endo, features = c("PLVAP", "ACKR1", "CCL14"), group.by = "endo.celltype", cols = "RdBu") +  ggtitle(NULL) + theme(axis.title.x = element_blank(), axis.title.y = element_blank()) + scale_y_discrete(limits= rev)

```

# figure 4k
```{r}
fgsea.degen.cmc <- read.csv("~/JH/HF/RData/results/fgsea_SejongIn_P_Deg_0vs1_FullROI_N_cellselection_Y_Cardiomyocytes_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2023-06-24condition1-condition0.csv")

fgsea.hyp.cmc <- read.csv("~/JH/HF/RData/results/fgsea_SejongIn_P_Hyp_0vs1_FullROI_N_cellselection_Y_Cardiomyocytes_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2023-06-24NA.csv")

fgsea.fib.cmc <- read.csv("~/JH/HF/RData/results/fgsea_SejongIn_P_Fib_0vs1_FullROI_N_cellselection_Y_Cardiomyocytes_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2023-06-24NA.csv")

fgsea.disarr.cmc <- read.csv("~/JH/HF/RData/results/fgsea_SejongIn_P_Disarray_0vs1_FullROI_N_cellselection_Y_Cardiomyocytes_ROI_large_Vent_LV_DsSelect_NES_HCMP_Y_OL_pcaplot_outlier_RE_PID_Fixation.interval_KR_Y2023-06-24NA.csv")

fgsea.degen.endo <- read.csv("~/JH/HF/RData/results/fgsea_SejongIn_P_Deg_0vs1_FullROI_N_cellselection_Y_Endothelial_cells_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2023-06-24NA.csv")

fgsea.hyp.endo <- read.csv("~/JH/HF/RData/results/fgsea_SejongIn_P_Hyp_0vs1_FullROI_N_cellselection_Y_Endothelial_cells_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2023-06-24NA.csv")

fgsea.fib.endo <- read.csv("~/JH/HF/RData/results/fgsea_SejongIn_P_Fib_0vs1_FullROI_N_cellselection_Y_Endothelial_cells_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2023-06-24NA.csv")

fgsea.disarr.endo <- read.csv("~/JH/HF/RData/results/fgsea_SejongIn_P_Disarray_0vs1_FullROI_N_cellselection_Y_Endothelial_cells_ROI_large_Vent_LV_DsSelect_NES_HCMP_Y_OL_pcaplot_outlier_RE_PID_Fixation.interval_KR_Y2023-06-24NA.csv")

fgsea.degen.fb <- read.csv("~/JH/HF/RData/results/fgsea_SejongIn_P_Deg_0vs1_FullROI_N_cellselection_Y_Fibroblasts_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2024-04-24NA.csv")

fgsea.hyp.fb <- read.csv("~/JH/HF/RData/results/fgsea_SejongIn_P_Hyp_0vs1_FullROI_N_cellselection_Y_Fibroblasts_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2024-04-24NA.csv")

fgsea.fib.fb <- read.csv("~/JH/HF/RData/results/fgsea_SejongIn_P_Fib_0vs1_FullROI_N_cellselection_Y_Fibroblasts_ROI_large_Vent_LV_DsSelect_Non_N_OL_pcaplot_outlier_RE_PID_Institute_Fixation.interval_KR_Y2024-04-24NA.csv")

fgsea.list.histo <- list()

fgsea.list.histo <- list(fgsea.hyp.cmc, fgsea.degen.cmc, fgsea.fib.cmc, fgsea.disarr.cmc, fgsea.hyp.endo, fgsea.degen.endo, fgsea.fib.endo, fgsea.disarr.endo, fgsea.hyp.fb, fgsea.degen.fb, fgsea.fib.fb)

hallmark.list.histo <- list()

for(i in 1:length(fgsea.list.histo)){
  hallmark.list.histo[[i]] <- fgsea.list.histo[[i]][fgsea.list.histo[[i]]$padj < 0.05,] 
  hallmark.list.histo[[i]] <- hallmark.list.histo[[i]]$pathway
}

sig.pathway.histo <- unlist(hallmark.list.histo)
sig.pathway.histo <- unique(sig.pathway.histo)

fgsea.list.histo.sig <- list()
for(i in 1:length(fgsea.list.histo)){
  fgsea.list.histo.sig[[i]] <- fgsea.list.histo[[i]][fgsea.list.histo[[i]]$pathway %in% sig.pathway.histo,] 
  fgsea.list.histo.sig[[i]] <- fgsea.list.histo.sig[[i]][,c(2,4,6)]
}

for(i in 1:4) {
  fgsea.list.histo.sig[[i]]$celltype <- "Cardiomyocyte"
  fgsea.list.histo.sig[[i+4]]$celltype <- "Endothelial cell"
  fgsea.list.histo.sig[[i+8]]$celltype <- "Fibroblast"
}

fgsea.hyp.cmc.sig <- fgsea.list.histo.sig[[1]]
fgsea.degen.cmc.sig <- fgsea.list.histo.sig[[2]]
fgsea.fib.cmc.sig <- fgsea.list.histo.sig[[3]]
fgsea.disarr.cmc.sig <- fgsea.list.histo.sig[[4]]
fgsea.hyp.endo.sig <- fgsea.list.histo.sig[[5]]
fgsea.degen.endo.sig <- fgsea.list.histo.sig[[6]]
fgsea.fib.endo.sig <- fgsea.list.histo.sig[[7]]
fgsea.disarr.endo.sig <- fgsea.list.histo.sig[[8]]
fgsea.hyp.fb.sig <- fgsea.list.histo.sig[[9]]
fgsea.degen.fb.sig <- fgsea.list.histo.sig[[10]]
fgsea.fib.fb.sig <- fgsea.list.histo.sig[[11]]

fgsea.hyp.cmc.sig$histology <- "Hypertrophy"
fgsea.degen.cmc.sig$histology <- "Degeneration"
fgsea.fib.cmc.sig$histology <- "Fibrosis"
fgsea.disarr.cmc.sig$histology <- "Disarray"
fgsea.hyp.endo.sig$histology <- "Hypertrophy"
fgsea.degen.endo.sig$histology <- "Degeneration"
fgsea.fib.endo.sig$histology <- "Fibrosis"
fgsea.disarr.endo.sig$histology <- "Disarray"
fgsea.hyp.fb.sig$histology <- "Hypertrophy"
fgsea.degen.fb.sig$histology <- "Degeneration"
fgsea.fib.fb.sig$histology <- "Fibrosis"


fgsea.hyp.cmc.sig$identity <- paste0(fgsea.hyp.cmc.sig$histology, "_", fgsea.hyp.cmc.sig$celltype)
fgsea.degen.cmc.sig$identity <- paste0(fgsea.degen.cmc.sig$histology, "_", fgsea.degen.cmc.sig$celltype)
fgsea.fib.cmc.sig$identity <- paste0(fgsea.fib.cmc.sig$histology, "_", fgsea.fib.cmc.sig$celltype)
fgsea.disarr.cmc.sig$identity <- paste0(fgsea.disarr.cmc.sig$histology, "_", fgsea.disarr.cmc.sig$celltype)
fgsea.hyp.endo.sig$identity <- paste0(fgsea.hyp.endo.sig$histology, "_", fgsea.hyp.endo.sig$celltype)
fgsea.degen.endo.sig$identity <- paste0(fgsea.degen.endo.sig$histology, "_", fgsea.degen.endo.sig$celltype)
fgsea.fib.endo.sig$identity <- paste0(fgsea.fib.endo.sig$histology, "_", fgsea.fib.endo.sig$celltype)
fgsea.disarr.endo.sig$identity <- paste0(fgsea.disarr.endo.sig$histology, "_", fgsea.disarr.endo.sig$celltype)
fgsea.hyp.fb.sig$identity <- paste0(fgsea.hyp.fb.sig$histology, "_", fgsea.hyp.fb.sig$celltype)
fgsea.degen.fb.sig$identity <- paste0(fgsea.degen.fb.sig$histology, "_", fgsea.degen.fb.sig$celltype)
fgsea.fib.fb.sig$identity <- paste0(fgsea.fib.fb.sig$histology, "_", fgsea.fib.fb.sig$celltype)

fgsea.identity.histo <- c("Hypertrophy_Cardiomyocyte", "Hypertrophy_Endothelial cell", "Hypertrophy_Fibroblast", "Degeneration_Cardiomyocyte", "Degeneration_Endothelial cell", "Degeneration_Fibroblast", "Fibrosis_Cardiomyocyte", "Fibrosis_Endothelial cell", "Fibrosis_Fibroblast", "Disarray_Cardiomyocyte", "Disarray_Endothelial cell")


fgsea.sort.histo.sig <- rbind(fgsea.hyp.cmc.sig, fgsea.degen.cmc.sig, fgsea.fib.cmc.sig, fgsea.disarr.cmc.sig, fgsea.hyp.endo.sig, fgsea.degen.endo.sig, fgsea.fib.endo.sig, fgsea.disarr.endo.sig, fgsea.hyp.fb.sig, fgsea.degen.fb.sig, fgsea.fib.fb.sig)


fgsea.sort.histo.sig$identity <- factor(fgsea.sort.histo.sig$identity,
                                  levels = fgsea.identity.histo)

fgsea.sort.histo.sig <- fgsea.sort.histo.sig %>% mutate(clas=ifelse(padj<0.05 & NES>0, "Positive", ifelse(padj<0.05 & NES<0, "Negative", "Insignificant")))

fgsea.order <- c("HALLMARK_MYOGENESIS", "HALLMARK_OXIDATIVE_PHOSPHORYLATION", "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION", "HALLMARK_INTERFERON_ALPHA_RESPONSE", "HALLMARK_INTERFERON_GAMMA_RESPONSE", "HALLMARK_FATTY_ACID_METABOLISM", "HALLMARK_ADIPOGENESIS", "HALLMARK_GLYCOLYSIS", "HALLMARK_HEME_METABOLISM", "HALLMARK_KRAS_SIGNALING_DN", "HALLMARK_TNFA_SIGNALING_VIA_NFKB", "HALLMARK_TGF_BETA_SIGNALING", "HALLMARK_HYPOXIA", "HALLMARK_COAGULATION", "HALLMARK_MTORC1_SIGNALING", "HALLMARK_KRAS_SIGNALING_UP", "HALLMARK_PROTEIN_SECRETION", "HALLMARK_MYC_TARGETS_V1", "HALLMARK_BILE_ACID_METABOLISM", "HALLMARK_ALLOGRAFT_REJECTION", "HALLMARK_ANGIOGENESIS", "HALLMARK_INFLAMMATORY_RESPONSE", "HALLMARK_IL6_JAK_STAT3_SIGNALING", "HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY", "HALLMARK_ANDROGEN_RESPONSE", "HALLMARK_P53_PATHWAY")

fgsea.sort.histo.sig.backup <- fgsea.sort.histo.sig
fgsea.sort.histo.sig$pathway <- factor(fgsea.sort.histo.sig$pathway,
                                       levels = fgsea.order)

fgsea.sort.histo.sig <- fgsea.sort.histo.sig %>%
  mutate(pvalue = ifelse(padj > 0.05, "white", "black"))


ggplot(fgsea.sort.histo.sig, aes(x = identity, y = pathway, fill = NES, color = pvalue)) +
  geom_point(aes(size = -log10(padj)), alpha = 1, shape = 21, stroke = 1) +
  scale_size_continuous(range = c(0.05,7)) +
  theme_bw() +
  #theme(axis.line = element_line(colour = "black", size = 0.8)) +
  theme(panel.grid = element_blank()) +
  #ylab("Proportion of Cells") +
  xlab("") +
  #theme(text = element_text(size=11)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_discrete(limits = rev(levels(fgsea.sort.histo.sig$pathway))) +
  #scale_y_continuous(expand = expansion(mult = c(0, 0))) +
  #guides(fill = guide_legend(ncol = 1)) +
  #theme(legend.key.height = unit(10, units = 'pt')) +
  scale_fill_gradientn(colors = brewer.pal(n = 11, name = "RdBu")[11:1], limits = c(min(fgsea.sort.histo.sig$NES), max(fgsea.sort.histo.sig$NES))) + 
  scale_color_manual(values = c("black", "white")) + 
  geom_vline(xintercept = xintercepts2, 
             color = "black", linetype = "dashed")
```

